name: haskell-in-depth
version: !include "./VERSION"
synopsis: Working through 'Haskell in Depth'
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/haskell-in-depth
dependencies:
- base
- text
ghc-options:
- -Wall
- -Werror
executables:
  vocab1:
    ghc-options:
    - -O2
    source-dirs: ch01
    main: vocab1.hs
    dependencies: []
