name: haskell-in-depth
version: !include "./VERSION"
synopsis: Working through 'Haskell in Depth'
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/haskell-in-depth
data-files:
- data/*.txt
dependencies:
- base
- formatting
- lens
- optparse-applicative
- text
- text-show
- trifecta
ghc-options:
- -Wall
- -Werror
library:
  source-dirs:
  - ch01
  - ch02
executables:
  vocab-builder:
    ghc-options:
    - -O2
    source-dirs: ch01
    main: vocab3.hs
  radar:
    ghc-options:
    - -O2
    source-dirs: ch02/radar
    main: Main.hs
    dependencies:
    - haskell-in-depth
tests:
  radar-tests:
    main: Test/Radar.hs
    source-dirs: test/radar
    dependencies:
    - haskell-in-depth
    - hedgehog
    - tasty
    - tasty-discover
    - tasty-hedgehog
    - tasty-hunit
