name: containers-mini
version: 0.0.1.0
synopsis: Working through 'Haskell in Depth'
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/haskell-in-depth
dependencies:
- base
- containers
ghc-options:
- -Wall
- -Werror
library:
  other-extensions: NoImplicitPrelude
  source-dirs: src
tests:
  stack:
    main: Main.hs
    ghc-options:
    - -O0
    - -threaded
    source-dirs: test
    dependencies:
    - containers-mini
    - tasty
    - tasty-discover
    - tasty-hunit
