name: du
version: 0.0.1.0
synopsis: du implementation in Haskell
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/haskell-in-depth
dependencies:
- base
- data-default
- data-default-class
- directory
- extra
- filepath
- lens
- mtl
- optparse-applicative
- text
- text-show
- unix-compat
default-extensions:
- NamedFieldPuns
- OverloadedStrings
- RecordWildCards
ghc-options:
- -Wall
- -Werror
library:
  source-dirs: src
executable:
  ghc-options:
  - -O2
  main: Main.hs
  source-dirs: app
  dependencies:
  - du
