name: nix-build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        skip_adding_nixpkgs_channel: true
    - name: Cachix
      uses: cachix/cachix-action@v8
      with:
        name: yurrriq
        skipPush: true
    - name: Build project
      run: nix build --show-trace --verbose
    - name: Run vocab-builer
      run: nix run .#vocab-builder -- --help
    - name: Run radar
      run: nix run .#radar
    - name: Run du
      run: nix run .#du -- --help
